branchName:  'issue-${issue.number}-${issue.title^}'
silent:      true
branches:
  - label: question
    skip: true
  - label: design
    skip: true
  - label: business
    skip: true
  - label: art
    skip: true
  - label: music
    skip: true
  - label: sound
    skip: true
  - label: gdd
    skip: true
  - label: writing
    skip: true
